project:
  type: website

website:
  title: "Bayesian Workflows course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule 
      - href: materials.qmd
        text: Materials
      #- text: "FAQ"
      # href: FAQ.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



