project:
  type: website

website:
  title: "Bayesian Workflows - Advanced Course"
  navbar:
    left:
      - href: materials.qmd
        text: Schedule and Content
      - href: template_workflow_diary.qmd 
        text: Workflow diary 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



