project:
  type: website

website:
  title: "Bayesian Workflows - Advanced Course"
  navbar:
    left:
      - href: materials.qmd
        text: Schedule and Content

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



