---
title: "Analysis Dataset Options"
---

If you do not have a dataset or research problem that you are bringing to the course, below are some options. If you have previously completed BDA, you can use your dataset/project - as long as you are meaningfully expanding on the analyses and research question.

Note that some datasets have been overused, and that the following ones are forbidden in this course (more can be added to this list so make sure to check it regularly):

- extremely common datasets like `titanic`, `mtcars`, `iris`, `penguins` (Palmer Archipelago, n=344)
- Baseball batting (used by Bob Carpenter's StanCon case study).
- Datasets used in the BDA course demos like `bodyfat`, `diabetes`, `roaches` etc.

### `metafor` Analysis Examples

The website for the `metafor` R package provides a large list of datasets and references for meta-analyses: [Analysis Examples](https://www.metafor-project.org/doku.php/analyses)

### `metadat` R Package

The `metadat` package also provides a large range of meta-analysis datasets: [`metadat`](https://wviechtb.github.io/metadat/)


### 'Awesome Public Datasets' Repository

The 'Awesome Public Datasets' GitHub repository provides a large number of datasets from multiple fields and study types: [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)

### Minimum Wage Study (Causal Inference)

This is a classic example from economics in which interest lies in the causal effect of unemployment benefits on employment: here a link to a [vignette](https://aaronmams.github.io/Card-Krueger-Replication/) that that replicates the [original paper's](https://davidcard.berkeley.edu/papers/njmin-aer.pdf) analysis

### `medicaldata` R Package

The `medicaldata` package provides several medical datasets: [`medicaldata`](https://higgi13425.github.io/medicaldata/)

