---
title: "Bayesian Workflows - Advanced Seminar"
---

This is the webpage for "CS-E407520 Special Course in Machine Learning and Data Science: Bayesian Workflows" - a seminar on Bayesian workflows at Aalto University targeted at master students and doctoral researchers.

In this seminar, we dive into some of the essential steps of Bayesian modelling workflows and their application to practical analysis problems. We will be exploring how these Bayesian modelling workflows can be applied to a range of research questions, as well as common issues and problems that you might encounter. Students are strongly encouraged to bring their own analysis/modelling problem to apply each step of the workflow.

You will become familiar with available software tools that can support different aspects of modelling like prior sensitivity checks, choosing regularising priors, or using model comparison and model averaging techniques. You will gain hands-on experience working with your own modelling problem.

### Prerequisites

Successful completion of [CS-E5710 Bayesian Data Analysis](https://avehtari.github.io/BDA_course_Aalto/index.html) or equivalent competence/experience with Bayesian data analysis.

The number of participants is limited to 30.

### Assessment

You will be assessed on your understanding of each of the workflow steps, the role they play in the Bayesian workflow, and how to apply them to real-world data.

- 5 ECTS
- Pass/Fail
- workflow diary
