---
title: "Course Schedule and Content 2024"
---

# Schedule Overview

The course is taught in period V (22 April – 3 June 2024) on Mondays from 14:15-16:00 in R030/A133 T5.

|  | Seminar Slides | Date |
|---------|:-----|:------:|
| Session 1 | [Slides](slides/session1.pdf) | 22 April 2024 |
| Session 2 | [Slides](slides/session2.pdf) | 29 April 2024 |
| Session 3 | [Slides](slides/session3.pdf) | 06 May 2024 |
| Session 4 | [Slides](slides/session4.pdf) [Example](examples/Session4Example.html) [Example Source](examples/Session4Example.qmd) | 13 May 2024 |
| Session 5 | [Slides](slides/session5.pdf) | 20 May 2024 |
| Session 6 | Slides | 27 May 2024 |
| Session 7 | Slides | 3 June 2024 |

# Schedule Detail

### Session 1: Introduction to Bayesian Workflows

##### Learning Outcomes for the Session

  - Understanding of why data analysis / statistical / Bayesian Workflows are needed (i.e., current problems)
  - Basic understanding of how Bayesian Workflows aim to solve problems
  - Basic understanding of steps in workflow

##### What the Session will Cover

  - Practicalities of course
    - Details of the grading/assessment
    - Timing/schedules
    - Where to find more information and support
  - Relationship to prior BDA project tasks
    - Concepts/tasks from BDA which will be relevant
  - Possible datasets and modelling problems
    - For students without their own
  - Exploratory data analysis in Bayesian Workflow

##### Recommended Resources for Next Session

  - A preprint on "Bayesian Workflow" by Gelman et al. (2020) [arXiv]( https://arxiv.org/abs/2011.01808)

### Session 2: Choosing an Initial Model

##### Learning Outcomes for the Session

  - How to specify a research question that can be answered with a statistical model
  - Awareness of tools and methods to aid in exploring data and formulating question
  - Awareness of common/standard modelling approaches for different questions
  - Students should have decided on their research question and at least 1 initial model

##### What the Session will Cover

  - Using exploratory data analysis to support the choice of initial models
  - Common models and modelling approaches for common research questions
    - e.g., observational, randomised study, purely exploratory, based on theory
  - Literature and best-practices can also help with model development
    - Using either an example or a student's dataset/problem as an example

##### Recommended Resources for Next Session

  - A talk on iterative model building and Bayesian workflows by Aki Vehtari: [video recording](https://www.youtube.com/watch?v=ppKpwtGy8KQ)

### Session 3: Prior Choices

##### Learning Outcomes for the Session

  - Develop awareness of impact of mis-specified priors
  - Understanding of approaches for specifying prior (i.e., prior elicitation)
  - Understanding of tools/methods for diagnosing prior sensitivity

##### What the Session will Cover

  - How to turn assumptions/knowledge into prior
    - Generative priors, penalised complexity, etc.
    - Connection to model expansion/choice/selection goals
    - Brief coverage of different topics for prior choice
  - How to assess prior choice
    - If the type of prior / prior properties do not align, etc.
    - Prior predictive checks
  - How to revise/modify a prior (if needed)

##### Recommended Resources for Next Session

  - A talk on "Why not to be afraid of priors (too much)" by Paul-Christian Bürkner at Bayes@Lund 2018: [slides](https://bayesat.github.io/lund2018/slides/paul_burkner_prior_slides.pdf) [video recording](https://www.youtube.com/watch?v=Uz9r8eV2erQ)
  
### Session 4: Model Checking: Posterior Predictive Checks & Calibration

##### Learning Outcomes for the Session

  - Understanding role of predictive checks in model-checking
  - Understanding of impact of different data types on approach (e.g., continuous vs discrete)
  - Familiarity with different graphical methods and tools for supporting checking

##### What the Session will Cover

  - Detecting, resolving, and reporting:
    - Prior sensitivity
    - Posterior predictive checks
    - Calibration

##### Recommended Resources for Next Session

### Session 5: Extending Models and Model Selection

##### Learning Outcomes for the Session

  - Understanding of how to extend a model to better address a research question, and if it is even needed
  - Understanding of how to select between different models, and whether this is necessary
  - Understanding of how to combine multiple models for increased performance

##### What the Session will Cover

  - Common methods for model expansion
    - Data-driven vs theory-driven
  - Common methods for model comparison, and interpreting the results of these
  - Alternatives to model selection
    - e.g., model averaging

##### Recommended Resources for Next Session

  - [Poststratification](https://mc-stan.org/docs/stan-users-guide/poststratification.html) in Stan User's Guide
  - A talk on "A biased tour of the uncertainty visualization zoo" by Matthew Kay: [video recording](https://www.youtube.com/watch?v=eyLxh_YY3Hw)
  - [Case study](https://users.aalto.fi/~ave/casestudies/Digits/digits.html) by Aki Vehtari on reporting the correct number of digits 
  - A paper on "The only thing that can stop bad causal inference is good causal inference" on by Rohrer, Schmukle, & McElreath (2022) [link to pdf](https://doi.org/10.1017/S0140525X21000789)
  
### Session 6: Interpreting and Presenting Model Results

##### Learning Outcomes for the Session

  - Using model quantities and results to assess whether research question has been answered
    - Reflecting on how/if initial question has changed throughout workflow process
    - Reflection on possible alternative expansions for research questions/models
  - Presenting model results accessibly

##### What the Session will Cover

  - How to extract and prepare results
    - e.g., using R packages such as `tidybayes` and `marginaleffects`
    - Further analysis of interesting effects (interactions, smooths, etc.)
  - Prior sensitivity for final conclusions (quantities/choices not sensitive to priors)
  - Brief introduction to alternative methods for constructing and reporting alternative models
    - e.g., Multiverse analysis

##### Recommended Resources for Next Session

### Session 7: Summary & Presentations

##### Learning Outcomes for the Session

  - Awareness of how workflow will differ between research questions
  - Reflection of how workflow contributed to analysis process
  - Reflection on future iterations of model

